apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-python-app
  name: simple-python-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: simple-python-app
status:
  loadBalancer: {}
