name: cicd-pipeline

on:
  push:
    paths: 
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Get short SHA
        id: slug
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shukritech/simple-python-app:${{ steps.slug.outputs.sha_short }}

  cd:
    runs-on: local-k8s-runners
    needs: ci
    steps:
      -
        name: Install and configure ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          mv argocd-linux-amd64 ./argocd
          
      -
        name: Login to ArgoCD
        run: |
          ./argocd login argocd-server.argocd \
            --username admin \
            --password ${{ secrets.ARGOCD_ADMIN_PASSWORD }} \
            --insecure \
            --plaintext \
            --grpc-web
            
      -
        name: Sync ArgoCD app
        run: ./argocd app sync app --grpc-web