name: cicd-pipeline

on:
  push:
    paths: 
      - src/**
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.slug.outputs.sha_short }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Get short SHA
        id: slug
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-6)" >> $GITHUB_OUTPUT

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shukritech/simple-python-app:${{ steps.slug.outputs.sha_short }}

  cd:
    runs-on: local-k8s-runners
    needs: ci
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        
      -
        name: Install and configure ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 http://argocd-server.argocd/download/argocd-linux-arm64
          chmod +x argocd-linux-amd64
          mv argocd-linux-amd64 ./argocd

      - 
        name: Modify value file to update image tag
        run: |
          echo ${{needs.ci.outputs.sha_short}}
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.sha_short}}"' 'charts/simple-python-app/values.yaml'

      - 
        name: commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: update image tag to ${{ needs.ci.outputs.sha_short }}"

      -
        name: Login and sync ArgoCD application
        run: |
          ./argocd login argocd-server.argocd \
            --username admin \
            --password ${{ secrets.ARGOCD_ADMIN_PASSWORD }} \
            --insecure \
            --plaintext \
            --grpc-web
          ./argocd app sync app --grpc-web